### ISSUE TITLE
Duplicate tiles / pieces

### ISSUE THREAD

**Issue by mknudsen** [julesbond007/android-jigsaw-puzzle#15]
I've noticed that the game duplicates tiles under certain conditions. The bug was fairly easy to produce by swapping two pieces repeatedly. I've recorded a short video demonstrating the issue. This was with API 23 in an emulator (as well as my device) with revision e22e6cf4c7d6c9b8d7c729ff90715955fa9ac2a7 of your app.

See https://youtu.be/0NPei9gyN_Y .

**Comment by julesbond007** [comment]
I haven't been able to dig through that bug, but if you find a solution, feel free to send a PR...thanks!

**Comment by julesbond007** [comment]
I believe it's fixed now!
